Makefile, merge-to-master-pipeline.yml, version.go
This PR makes azure build pipelines use the correct compilers for windows and compiles each DLL and .so file separately and uploads it to a github release
=> Make azure pipeline build x86 and amd64 windows dlls

version.go
We had a docs-only PR before this that didn't bump the version,
and the merge-to-master build failed, and the latest release
doesn't have that docs change.
=> Bump version to 1.1.6

README.md, nrclient/proxy.go, version.go
There are 2 kinds of proxies that are able to forward HTTPS traffic:
1. "Plain HTTPS proxies", which can potentially inspect the traffic sent by its clients. The clients need to accept its certificate, and need to first send a FORWARD (CONNECT) request to establish the connection, prior to the TLS handshake.
2. "TCP proxies", which don't require HTTPS specifically to work and therefore should handle the TLS handshake without any prior HTTP CONNECT initiator.
Go 1.10 introduced a breaking change with regards to this: proxied HTTPS connections are established using a single plain TCP based TLS handshake (with no prior HTTP CONNECT initiator), which only works in "TCP Proxies" (like Squid). Therefore, "Plain HTTPS proxies" (like Charles) cannot work in this setup.
The `infra-agent` team has …
=> LOGGING-2378: Fixes HTTPS proxy support and improves documentation

record/record.go, record/record_test.go, version.go
The current implementation of the plugin doesn't support parsing a JSON having an array of JSON objects inside of it. The field ends up becoming a []interface{}, which then contains a list of map[interface{}]interface{}. This scenario is not currently handled (it’s missing a clause for []interface{} here), and then the resulting object contains a `map[interface{}]interface{}` which cannot be converted back to JSON.
The introduced change includes a unit test precisely testing the buggy scenario
=> LOGGING-2555: Adds support for JSON arrays within a log record

.github/workflows/merge-to-master.yml, .github/workflows/pr.yaml, Dockerfile_firelens, version.go
This PR adds the automatic building of Firelens AWS images (see docs [here](https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/aws-firelens-plugin-log-forwarding/)), both as part of the PR and when merging to the main branch. When merging to the main branch, it also publishes automatically to the related Newrelic's AWS ECR repository.
=> [LOGGING-4394] Testing Firelens automatic publishing

Dockerfile, Dockerfile_debug, Dockerfile_firelens, version.go
This PR updates the fluent-bit version to 1.8.1 in all Dockerfiles
- Dockerfile
- Dockerfile_debug
- Dockerfile_firelens
In the firelens one we're using aws-for-fluent-bit 2.1.7, which includes fluent bit 1.8.1 (https://github.com/aws/aws-for-fluent-bit/releases/tag/2.17.0)
=> [LOGGING-5152] Update fluent bit to 1.8.1

.github/workflows/pr.yaml, .gitignore, README.md, test.sh, test/docker-compose.yml, test/expectations.json, test/fluent-bit.conf, test/verification.json
Adding tests for docker images on the pipeline, also updated the README but here are the steps followed by test scripts:
1. Create test/testdata folder for store temporal configurations and the log file
2. Build the image (default dockerfile is ./Dockerfile but you can set the one you want with DOCKERFILE env)
3. Run the docker-compose (./test/docker-compose.yml) with the following instances:
- A mockserver with expectations from ./test/expectations.json
- The built docker image with fluent bit configuration from ./test/fluent-bit.conf
4. Send some logs
5. Verify that logs are reaching the mockserver
6. Cleanup
=> [LOGGING-5125] Add docker image tests to the pipeline

.github/workflows/merge-to-master.yml, .github/workflows/pr.yaml, Dockerfile_arm64, README.md, test.sh, version.go
From @saibaldey [PR#79](https://github.com/newrelic/newrelic-fluent-bit-output/pull/79)
New version of output plugin v1.7.0 will provide support for arm64 docker images.
In this PR:
- New docker file will allow customers to build arm images locally
- Provide arm64 docker image support by: `docker pull newrelic/newrelic-fluentbit-output:1.7.0-arm64`
=> feat: build and push output arm64 docker image

out_newrelic.go, version.go
Drop log line of the happy path. 
Solves this issue: https://github.com/newrelic/newrelic-fluent-bit-output/issues/87
=> Removes verbose log

.github/workflows/merge-to-master.yml, .github/workflows/pr.yaml, Dockerfile.windows, version.go
This PR includes a new `Dockerfile.windows` file to build a Docker image for the Windows platform.
Windows container support is still very limited. There is a huge restriction: Windows Docker containers can only be built/executed on a host node running the same operating system version and compilation build as the container it builds/executes.
Right now, Kubernetes some versions, being the LTSC 2019 the recommended one. It also supports several SAC versions. However, the `windows-2019` worker that GitHub actions provides is based on LTSC 2019 / 10.0.17763.2183, and can't therefore build SAC versions. This is why, for now, we restrict the build to only happen for this Windows version.
The Dockerfile contents continue the work initiated by @andrew-lozoya, and also includes the Dockerfile …
=> [LOGGING-5582] Build Windows Server 2019 LTSC Docker image

.github/workflows/pr.yaml, nrclient/nrclient_test.go, version.go
This adapts the unit tests to the logic introduced on #96
=> Fix: adapt unit tests to new retry logic

Dockerfile, Dockerfile.windows, Dockerfile_debug, Dockerfile_firelens, version.go
Release notes from dependencies:
ec5a857b07ff08fae3048fdcc13f1a14da3f53f5, 5a27fcbf1eca4c8757f4624789c60d203b77ed3a fb +debug -> [v1.8.12](https://fluentbit.io/announcements/v1.8.12/)
45d136de004dfca6b3e477aba6fd5b5edff4b258 firelens -> aws/aws-for-fluent-bit [v1.21.5](https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.22.0)
15b6ea71768f879594d503bcd2062a586eb8067e windows ??? 🤷‍♀️
Solves #102
=> feat: update fb v1.8.12

nrclient/proxy_windows.go, version.go
Many customers using our plugin under Windows (either with a standalone Fluent Bit installation or by using the Infrastructure Agent) have been confused by this message, originally emitted as a `WARNING`. This was just an informative message, so I've reduced its level to `Info`. Moreover, given that now we have proper documentation around setting up self-signed certificates on Windows in our GitHub readme, I've included a link instead of a longer (and probably confusing) text.
=> Improve misleading message that causes lots of confusion for customers

Dockerfile, Dockerfile.windows, Dockerfile_debug, Dockerfile_firelens, go.mod, vendor/modules.txt, version.go
This PR addresses:
- Upgrades Docker images to use Fluent Bit 1.9.9.
- Upgrades Go to 1.14 in the Docker builder images, so it is in line with [the version that we were using](https://github.com/newrelic/newrelic-fluent-bit-output/blob/master/.github/workflows/merge-to-master.yml#L14-L17) when [building the standalone plugin](https://github.com/newrelic/newrelic-fluent-bit-output/blob/master/.github/workflows/merge-to-master.yml#L36-L49) (which is [used by the Infrastructure Agent](https://github.com/newrelic/infrastructure-agent/blob/e0fc2d4f8faf2405abb25c7fde66150b85213575/build/embed/fluent-bit.mk#L13)).
The upgrade to Go 1.14 was necessary since some `go get` statements were failing when building the Docker images. This made me realise that we were using Go 1.11 in the Docker builder, …
=> Upgrades Docker images to be based on Fluent Bit 1.9.9 and Go in Docker images to 1.14

record/record.go, record/record_test.go, version.go
If the received record contains a valid `int64` `timestamp` attribute,
we use this as the `timestamp`.
Otherwise use fluentbit's observed `timestamp`.
=> Use Record's timestamp preferably

.github/workflows/merge-to-master.yml, .github/workflows/pr.yaml
In order for a windows node to run a windows container image, both need to match the exact version and build number.
Currently we only support [Windows Server 2019 (LTSC)](https://github.com/newrelic/helm-charts/blob/master/charts/newrelic-logging/values.yaml#L176).
This PR adds building an image for Windows 2022 (LTSC) allowing our plugin to run on Windows 2022 (LTSC) hosts. 
References
- https://kubernetes.io/docs/concepts/windows/intro/#windows-os-version-support
=> Adds support to run on Windows Server 2022 (LTSC)

.github/workflows/merge-to-master.yml, .github/workflows/pr.yaml, .github/workflows/repolinter.yml, nrclient/nrclient.go, nrclient/nrclient_test.go, record/record_test.go, version.go
Right now if a retriable error happens we're not able to see which HTTP status code was.
This adds the status code as an error on the nrclient and will be logged by out_newrelic.
=> Inform the http status code for retriable requests

Dockerfile, Dockerfile.windows, Dockerfile_debug, Dockerfile_firelens, version.go
These changes in the FluentBit image remove the vulnerability [CVE-2021-46848](https://security-tracker.debian.org/tracker/CVE-2021-46848)
- Bumped FluentBit Windows and Linux to v2.0.8
- Bumped FluentBit for AWS to v2.31.8 (based on FluentBit 1.9.10)
- Updated Dockerfile.windows to support FluentBit 2.0.8
=> feat: Upgraded FluentBit version to 2.0.8/1.9.10

.github/workflows/merge-to-master.yml, .github/workflows/pr.yaml, Dockerfile, Dockerfile.windows, Dockerfile_debug, Dockerfile_firelens, version.go
golang < 1.20.5 contains some vulnerability problems, so this upgrade the golang to 1.20.5 (the latest golang version)
=> Upgrade golang to 1.20.5

Dockerfile, Dockerfile.windows, Dockerfile_debug, Dockerfile_firelens, version.go
By #133 looks like the previous change break ECR/ECS integrations that uses the Firelens image. Rolling back that change while investigate.
=> Rollback golang image used by docker firelens image

.github/workflows/merge-to-master.yml
This is only for apt update before installing as there are dependencies that can't be found and looking at the repos they had been updated
=> Add apt update

Dockerfile, Dockerfile.windows, Dockerfile_debug, Dockerfile_firelens, version.go
golang 1.14 have many vulnerabilities reported so this will upgrade docker images to latest version.
Previous release trying this used golang:1.20.5 which break all the docker images, now we're tying to golang:1.20.5-buster to avoid problems with glibc version included in fluent-bit image.
=> Upgrade golang in docker images to 1.20.5

Dockerfile, Dockerfile.windows, Dockerfile_debug, record/record.go, record/record_test.go, version.go
* Upgraded Fluent Bit version to 2.2.0. 
* Fluent Bit version for FireLens remains without changes
* Updated Output plugin to support the extraction of timestamp from Fluent Bit Event nested array according to the new format introduced in v2.1.0
* Added unit tests for timestamps in Event nested array
* Upgraded Logging Output plugin version to 1.19.0
=> feat: bump Fluent Bit version to 2.2.0. 

.github/workflows/merge-to-master.yml, .github/workflows/pr.yaml, Dockerfile, Dockerfile.windows, Dockerfile_debug, Dockerfile_firelens, go.mod, version.go
Go 1.21 introduced a bug that causes Fluent Bit to crash when using our plugin. This was reported [here](https://github.com/golang/go/issues/62130#issuecomment-1687335898) as well.
We had inconsistent Go versioning in the plugins we publish:
- The Go version used to compile our "standalone" plugin *.so files was `^1.20.5`, meaning that any version past that one could be used to compile them. In our 1.18.0 plugin, Go `1.21.4` was actually used. This is what "allowed" us to detect the issue. To avoid this happening again, we will pin the version to ~~1.20.12~~ `1.20.7` strictly.
- The Go version used to compile our plugin in the Docker images was actually `1.20.5` (strict), as we are using the official golang buster images. This is what prevented the problem from happening in the Docker …
=> Pin Go to 1.20.12 due to https://github.com/golang/go/issues/62130

.github/workflows/merge-to-master.yml, .github/workflows/pr.yaml, Dockerfile.windows
* Updated GitHub actions to generate debug image for `linux/arm64` platform.
* Changes in `Dockerfile.windows` according to the last updated in the [official repo](https://github.com/fluent/fluent-bit/pull/8463/files)
=> feat: generate debug image for linux/arm64 platform

Dockerfile, Dockerfile.windows, Dockerfile_debug, version.go
This fixes the following vulnerabilities added by libpq5
**HIGH**
[CVE-2023-39417](https://avd.aquasec.com/nvd/cve-2023-39417): postgresql: extension script `@substitutions@` within quoting allow SQL injection
[CVE-2023-5869](https://avd.aquasec.com/nvd/cve-2023-5869): postgresql: Buffer overrun from integer overflow in array modification
**MEDIUM**
[CVE-2023-5868](https://avd.aquasec.com/nvd/cve-2023-5868): postgresql: Memory disclosure in aggregate function calls
[CVE-2023-5870](https://avd.aquasec.com/nvd/cve-2023-5870): postgresql: Role pg_signal_backend can signal certain superuser processes.
=> Bump fluent bit base image to 2.2.2

README.md
Adds instructions on how to mount your own  `fluent-bit.conf` and be able to set up other configuration options of our plugin.
=> Improve readme when running from Docker container

version.go
Today, July 10th 2024, we have enabled the newrelic-fluent-bit-output Firelens Docker image replication to the new following AWS regions:
- `af-south-1`: Africa (Cape Town)
- `ca-west-1`: Canada (Calgary)
- `eu-central-2`: Europe (Zurich)
- `eu-south-1`: Europe (Milan)
- `eu-south-2`: Europe (Spain)
- `me-central-1`: Middle East (UAE)
- `me-south-1`: Middle East (Bahrain)
Merging this commit will publish a new image and have it replicated to the aforementioned regions.
=> Trigger Firelens image publishing in new regions

.github/workflows/pr.yaml, Dockerfile, Dockerfile.windows, Dockerfile_debug, Dockerfile_firelens, version.go
Built the image locally on Mac computer,  ran it and validated the logs receiving on the Newrelic.
Modified the fluent-bit.conf file as follows to pass to the docker run command:
```
[SERVICE]
Flush         1
Daemon        Off
Log_File      /dev/stdout
Log_Level     debug
[INPUT]
Name          tail
Path          /test-log/test/test.log
[OUTPUT]
Name          newrelic
Match         *     
licenseKey    xxxx
```
then created a test.log file with sample log messages written into it. test.log:
```
This is Rajeev testing on 10th Feb 2025, 5.29pm
This is Again Rajeev testing 10th Feb 2025, 5.35pm
```
Built the docker images using the following commands and ran it by mounting the volume locally:
```
docker build -t rkallempudi/newrelic-fluentbit-output . 
docker run -v …
```
=> Bump fluent-bit to 3.2.2 and go version to 1.23.x

.github/workflows/pr.yaml, Dockerfile, Dockerfile.windows, Dockerfile_debug, version.go
This PR attempts to bump up fb version to 3.2.7 to address the following CVEs:
https://fluentbit.io/announcements/v3.2.7/#:~:text=OpenTelemetry%20input%3A,CVE%2D2024%2D50608
=> bump up fluent bit version to 3.2.7
